---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ21N18"
  stages:
    Acceptance:
      cfCredentialsId: "cfdeploy"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Acceptance:
    cfApiEndpoint: "https://api.cf.jp10.hana.ondemand.com"
    cfOrg: "UMC Electronics Co., Ltd._s01-test"
    cfSpace: "DEV"
    deployType: "standard"
    cloudFoundryDeploy: true
    npmExecuteEndToEndTests: false
  Malware Scan:
    malwareExecuteScan: false
  Release:
    tmsExport: false
    tmsUpload: false
    cloudFoundryDeploy: false
  Additional Unit Tests:
    npmExecuteScripts: false
  Compliance:
    sonarExecuteScan: false
steps:
  mtaBuild:
    source: mta_umceq
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
